all opt lib:
	@echo ""
	@echo You need to use the OMake tool in order to build this software!
	@echo ""
	@echo Download OMake from http://projects.camlcity.org/projects/omake.html
	@echo Source packages, Git repository, and Documentation set are available.
	@echo ""
	@exit 1
